### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by volovyks** [sig-net/mpc#25]
```[tasklist]
### Tasks
- [ ] https://github.com/near/transfer/issues/23
- [ ] https://github.com/near/transfer/issues/14
- [ ] https://github.com/near/transfer/issues/16
- [ ] https://github.com/near/mpc/issues/783
- [ ] https://github.com/near/mpc/issues/859
- [ ] https://github.com/near/mpc/issues/854
- [ ] https://github.com/near/mpc/issues/850
- [ ] https://github.com/near/mpc/issues/852
- [ ] https://github.com/near/mpc/issues/885
- [ ] https://github.com/near/mpc/issues/893
- [ ] https://github.com/near/transfer/issues/15
- [ ] https://github.com/near/transfer/issues/20
```
