### ISSUE TITLE
Transparancy and docs

### ISSUE THREAD

**Issue by volovyks** [sig-net/mpc#29]
```[tasklist]
### Tasks
- [ ] https://github.com/near/mpc/issues/863
- [ ] https://github.com/near/mpc/issues/860
- [ ] https://github.com/near/mpc/issues/861
- [ ] https://github.com/near/mpc/issues/862
- [ ] https://github.com/near/mpc/issues/877
- [ ] https://github.com/near/transfer/issues/37
- [ ] https://github.com/near/transfer/issues/22
```
