### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by volovyks** [sig-net/mpc#30]
### Description

```[tasklist]
### Tasks
- [ ] https://github.com/near/transfer/issues/32
- [ ] https://github.com/near/transfer/issues/34
- [ ] https://github.com/near/transfer/issues/31
- [ ] https://github.com/near/transfer/issues/29
```
