### ISSUE TITLE
investigation: 5+% signature failure and 20% presignature failure and 15% triple failure

### ISSUE THREAD

**Issue by ppca** [sig-net/mpc#42]
```[tasklist]
### Tasks
- [ ] https://github.com/near/transfer/issues/17
- [ ] https://github.com/near/transfer/issues/18
- [ ] https://github.com/near/transfer/issues/19
- [ ] https://github.com/near/mpc/issues/851
```

**Comment by volovyks** [comment]
This issues is still relevant

![Image](https://github.com/user-attachments/assets/3f0f0148-3de1-462f-a53f-bdba07e7c0db)

**Comment by volovyks** [comment]
Our protocol success rates look good now.
